apiVersion: v1
kind: Service
metadata:
  name: studentsurveyfrontendservice
spec:
  type: NodePort
  selector:
    app: studentsurveyfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      nodePort: 32005
